services:
  postgres:
    image: postgres:16-alpine
    container_name: clinicflow-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clinicflowDB

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  backend:
    build:
      context: ./backend

    container_name: clinicflow-backend

    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: clinicflowDB
      DB_PASSWORD: root
      DB_PORT: 5432
      JWT_SECRET: ClinicFlow_Docker_Secret_2026

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend

    container_name: clinicflow-frontend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:5000/api

    depends_on:
      - backend

volumes:
  postgres_data: